/*
 * Copyright 2019 Sysfoundry (www.sysfoundry.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.sysfoundry.kiln.base.evt;

import com.github.krukow.clj_ds.PersistentMap;
import com.github.krukow.clj_lang.PersistentHashMap;
import lombok.Value;

import java.time.Instant;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * This class represents the Event abstraction in Kiln.
 * Events have the following properties in Kiln
 * <ol>
 *     <li>id - Identifier of the event. In Kiln id is a random UUID generated by the system</li>
 *     <li>name - The name of the event</li>
 *     <li>time - The instant at which the event was generated</li>
 *     <li>data - A Map of data associated if any with the event</li>
 * </ol>
 */
@Value
public class Event {

    private final UUID id = UUID.randomUUID();
    private String name;
    private Instant time;
    private Map<String,Object> data;

    /**
     * Factory method to create events
     * @param name The name of the event
     * @param data The data associated with the event.
     * @return The created event instance
     */
    public static Event create(String name,Map<String,Object> data){
        Optional<Map<String,Object>> optionalData = Optional.ofNullable(data);
        Map<String,Object> dataMap = null;
        if(optionalData.isPresent()){
            dataMap = PersistentHashMap.create(optionalData.get());
        }else{
            dataMap = PersistentHashMap.emptyMap();
        }

        return new Event(name,Instant.now(),dataMap);
    }

    /**
     * Factory method to create an event only given its name
     * @param name The name of the event
     * @return The created event instance
     */
    public static Event create(String name){
        return create(name, PersistentHashMap.emptyMap());
    }

}
